### ISSUE TITLE
programador/index.md

### ISSUE THREAD

**Issue by wchiquito** [esparta/97cosas#10]
---
layout: programador
title: 97 cosas que todo programador debería saber
overview: true
---

Traducción al Español del libro "[97 Things Every Programmer Should Know](http://programmer.97things.oreilly.com/wiki/index.php/97_Things_Every_Programmer_Should_Know)", contiene todo tipo de consejos y recomendaciones para los profesionales de la programación informática: refactorización, código limpio, pruebas, aprendizaje contínuo, etc.

Este sitio es la continuación del esfuerzo de Natán Calzolari (inicialmente en http://97cosas.com.ar), a quien agradezco de su iniciativa.

## Índice

1. [Actúa con prudencia](actua-con-prudencia.html), por Seb Rose
2. [Aplica los principios de la programación funcional](aplica-programacion-funcional.html), por Edward Garson
3. [Averigua qué haría el usuario (tú no eres el usuario)](averigua-que-haria-usuario.html), por Giles Colborne
4. [Automatiza el estándar de codificación](automatiza-estandar-codificacion.html), por Filip van Laenen
5. [La belleza está en la simplicidad](belleza-simplicidad.html), por Jørn Ølmheim
6. [Antes de Refactorizar](antes-de-refactorizar.html), por Rajith Attapattu
7. [Ten cuidado al compartir](cuidado-al-compartir.html), por Udi Dahan
8. [La Regla Boy Scout](regla-boy-scout.html), por Uncle Bob
9. [Primero revisa tu código antes de buscar culpar a otros](revisa-tu-codigo.html), por Allan Kelly
10. [Escoge tus herramientas con cuidado](escoge-herramientas-con-cuidado.html), por Giovanni Asproni
11. [Codifica en el lenguaje del dominio](codifica-en-lenguaje-del-dominio.html), por Dan North
12. [El código es diseño](codigo-es-disenno.html), por Ryan Brush
13. [El diseño del código sí importa](diseno-en-codigo-importa.html), por Steve Freeman
14. [Revisiones de código](revisiones-codigo.html), por Mattias Karlsson
15. [Codificando con la razón](codifica-con-la-razon.html), por Yechiel Kimchi
16. [Un comentario acerca de los comentarios](comentario-acerca-de-comentarios.html), por Cal Evans
17. [Comenta sólo lo que el código no dice](comenta-codigo-no-dice.html), por Kevlin Henney
18. [Aprendiendo continuamente](aprendiendo-continuamente.html), por Clint Shank
19. [La conveniencia no es una -bilidad](conveniencia.html), por Gregor Hohpe
20. [Implementa rápido y con frecuencia](implementa-rapido-y-con-frecuencia.html), por Steve Berczuk
21. [Distingue excepciones de Negocio de las excepciones Técnicas](distingue-excepciones-negocio-tecnicas.html), por Dan Bergh Johnsson
22. [Haz mucha práctica deliberada](haz-mucha-practica-deliberada.html), por Jon Jagger
23. [Lenguajes Específicos del Dominio (DSL)](dsl.html), por Michael Hunger
24. [No tengas miedo de romper cosas](no-tengas-miedo-de-romper-cosas.html), por Mike Lewis
25. [No seas lindo con tus datos de prueba](no-seas-lindo-pruebas.html), por Rod Begbie
26. [¡No ignores ese error!](no-ignores-error.html), por Pete Goodliffe
27. [No sólo aprendas el lenguaje, entiende su cultura](no-aprendas-lenguaje-entiende-su-cultura.html), por Anders Norås
28. [No claves tu programa en la posición vertical](no-claves-programa.html), por Verity Stob
29. [No confíes en el "Aquí sucede la magia"](no-confies-magia.html), por AlanGriffiths
30. [No te repitas](no-te-repitas.html), por Steve Smith
31. [¡No toques ese código!](no-toques-ese-codigo.html), por Cal Evans
32. [Encapsula Comportamiento, no sólo Estado](encapsula-comportamiento.html), por Einar Landre
33. [Los números de punto flotante no son reales](numeros-punto-flotante.html), por Chuck Allison
34. [Cumple tus ambiciones con Software Libre](cumple-ambiciones-con-software-libre.html), por Richard Monson-Haefel
35. [La regla de oro del diseño de API](regla-oro-api.html), por Michael Feathers
36. [El mito del Gurú](el-mito-del-guru.html), por Ryan Brush
37. [El trabajo duro no paga](el-trabajo-duro-no-paga.html), por Olve Maudal
38. [¿Cómo usar un Gestor de Errores?](como-usar-bug-tracker.html), por Matt Doar
39. [Mejora el código quitándolo](mejora-codigo-quitandolo.html), por Pete Goodliffe
40. [Instalame](instalame.html), por Marcus Baker
41. [La comunicación entre procesos afecta el tiempo de respuesta de la aplicación](ipc-afecta.html), por Randy Stafford
42. [Mantén limpia la compilación](manten-limpia-compilacion.html), por Johannes Brodwall
43. [Aprende a usar las herramientas de línea de comandos](aprende-usar-linea-comando.html), por Carroll Robinson
44. [Conoce bien más de dos lenguajes de programación](conoce-bien-dos-lenguajes.html), por Russel Winder
45. [Conoce tu IDE](conoce-tu-ide.html), por Heinz Kabutz
46. [Conoce tus límites](conoce-tus-limites.html), por Greg Colvin
47. [Conoce tu próximo Commit](conoce-proximo-commit.html), por Dan Bergh Johnsson
48. [Los grandes datos interconectados pertenecen a una base de datos](datos-interconectados-pertenecen-base-de-datos.html), por Diomidis Spinellis
49. [Aprende un lenguaje extranjero](aprende-lenguaje-extranjero.html), por Klaus Marquardt
50. [Aprende a hacer estimaciones](aprende-estimaciones.html), por Giovanni Asproni
51. [Aprende a decir "Hola, Mundo"](aprende-decir-hola-mundo.html), por Thomas Guest
52. [Deja que tu proyecto hable por sí mismo](deja-proyecto-hable-por-si-mismo.html), por Daniel Lindner
53. [El linker no es un programa mágico](linker-no-magico.html), por Walter Bright
54. [La longevidad de las soluciones provisionales](longevidad-soluciones-provisionales.html), por Klaus Marquardt
55. [Haz las Interfaces fáciles de usar correctamente y difíciles de usar incorrectamente](interfaces-faciles-usar.html), por Scott Meyers
56. [Haz lo invisible más visible](haz-lo-invisible-mas-visible.html), por Jon Jagger
57. [El paso de mensajes lleva a una mejor escalabilidad en sistemas paralelos](paso-mensajes-mejor-escalabilidad.html), por Russel Winder
58. [Mensaje al futuro](mensaje-al-futuro.html), por Linda Rising
59. [Oportunidades perdidas del Polimorfismo](oportunidades-perdidas-polimorfismo.html), por Kirk Pepperdine
60. [Noticias raras - Los testers son tus amigos](testers-amigos.html), por Burk Hufnagel
61. [Un binario](un-binario.html), por Steve Freeman
62. [Sólo el código dice la verdad](solo-codigo-dice-verdad.html), por Peter Sommerlad
63. [Adueñate (y Refactoriza) la compilación](aduenate-build.html), por Steve Berczuk
64. [Programa en pareja y siente el flujo](programa-en-pareja-siente-flujo.html), por Gudny Hauknes, Ann Katrin Gagnat, y Kari Røssland
65. [Da preferencia a tipos de Dominio Específico que los tipos primitivos](preferencia-tipos-dominio-especifico.html), por Einar Landre
66. [Evita errores](evita-errores.html), por Giles Colborne
67. [El Programador Profesional](el-programador-profesional.html), por Uncle Bob
68. [Pon todo bajo Control de Versiones](pon-todo-bajo-control-de-versiones.html), por Diomidis Spinellis
69. [Suelta el ratón y aléjate del teclado](suelta-raton-alejate-teclado.html), por Burk Hufnagel
70. [Lee el código](lee-el-codigo.html), por Karianne Berg
71. [Lee las humanidades](lee-humanidades.html), por Keith Braithwaite
72. [Reinventa la rueda frecuentemente](reinventa-rueda-frecuentemente.html), por Jason P Sage
73. [Resiste la tentación del patrón Singleton](resiste-tentacion-singleton.html), por Sam Saariste
74. [El camino al mejor rendimiento está lleno de sucias bombas de código](camino-al-rendimiento-bombas-codigo.html), por Kirk Pepperdine
75. [La Simplicidad viene de la Reducción](simplicidad-reduccion.html), por Paul W. Homer
76. [El Principio de Responsabilidad Única](principio-responsabilidad-unica.html), por Uncle Bob
77. [Inicia con un Sí](inicia-con-un-si.html), por Alex Miller
78. [Retrocede y Automatiza, Automatiza, Automatiza](retrocede-automatiza.html), por Cay Horstmann
79. [Toma ventaja de las herramientas de análisis de código](toma-ventaja-analisis-codigo.html), por Sarah Mount
80. [Prueba el comportamiento requerido, no el comportamiento incidental](prueba-comportamiento-requerido-no-incidental.html), por Kevlin Henney
81. [Prueba precisa y concretamente](prueba-precisa-concretamente.html), por Kevlin Henney
82. [Haz pruebas mientras duermes (y los fines de semana)](pruebas-fin-de-semana.html), por Rajith Attapattu
83. [Las pruebas son el rigor ingenieril del desarrollo de software](pruebas-son-rigor-ingenieril.html), por Neal Ford
84. [Pensando en estados](pensando-en-estados.html), por Niclas Nilsson
85. [Dos cabezas son a menudo mejores que una](dos-cabezas-mejor-una.html), por Adrian Wible
86. [Dos fallos pueden hacer un acierto (y es difícil de arreglar)](dos-fallos-pueden-hacer-acierto.html), por Allan Kelly
87. [Codificación Ubuntu para tus amigos](codificacion-ubuntu.html), por Aslam Khan
88. [Las herramientas Unix son tus amigas](herramientas-unix-amigas.html), por Diomidis Spinellis
89. [Usa el algoritmo y estructura de datos correcto](usa-algoritmo-estructura-de-datos-correcto.html), por JC van Winkel
90. [Los registros detallados perturbarán tu sueño](registros-detallados-quitaran-sueno.html), por Johannes Brodwall
91. [El WET dispersa los cuellos de botella en el rendimiento](wet-dispersa-cuellos-de-botella.html), por Kirk Pepperdine
92. [Cuando Programadores y Testers colaboran](cuando-programadores-testers-colaboran.html), por Janet Gregory
93. [Escribe código como si tuvieras que mantenerlo por el resto de tu vida](escribe-codigo-mantenerlo-por-vida.html), por Yuriy Zubarev
94. [Escribe pequeñas funciones usando ejemplos](escribe-funciones-con-ejemplos.html), por Keith Braithwaite
95. [Escribe las pruebas para las personas](escribe-pruebas-para-personas.html), por Gerard Meszaros
96. [Preocúpate por el código](preocupate-por-el-codigo.html), por Pete Goodliffe
97. [Tus clientes no quieren decir lo que dicen](tus-clientes.html), por Nate Jackson

**Comment by esparta** [comment]
No entiendo muy bien que pasó aquí, pero voy a cerrar este issue en via de mientras, si tienes mas detalles por favor comenta, @wchiquito

**Comment by wchiquito** [comment]
Se ordena el listado según el listado original en inglés.

**Comment by esparta** [comment]
Puedes enviar un PR con los cambios?

**Comment by wchiquito** [comment]
PR enviado. Cierro este issue.
