### ISSUE TITLE
Texto: codifica-con-la-razon.html punto 10

### ISSUE THREAD

**Issue by pixelead0** [esparta/97cosas#11]
En la pagina codifica-con-la-razon.html en el punto 10 dice:
"Esto significa que los getters que regresan estados internos son una liabilidad"
Podría traducirse como:
"Esto significa que los getters que regresan estados internos son una reponsabilidad"

El texto original es:
"This means that getters that return internal state are a liability"

Referencias:
http://www.wordreference.com/es/translation.asp?tranword=liability
http://es.bab.la/diccionario/ingles-espanol/liability

**Comment by esparta** [comment]
Closed by #14 
Gracias, @pixelead0 !
