### ISSUE TITLE
Formateo para lectura en cualquier visor de texto

### ISSUE THREAD

**Issue by xiam** [esparta/97cosas#3]
Podríamos aprovechar todos los beneficios de markdown, como legibilidad en cualquier visor de texto, desde Eclipse IDE hasta `cat file.md | less`, para ésto el texto debería estar formateado a 80 columnas e incluir los hipervínculos al fondo, como referencias.

Podemos ver un ejemplo de mejora de visualización comparando el [documento original](https://raw.github.com/esparta/97cosas/gh-pages/programador/actua-con-prudencia.md), con un [documento alternativo](https://raw.github.com/xiam/97cosas/gh-pages/programador/actua-con-prudencia.md) formateado a 80 columnas y con hipervínculos al fondo.

Otro gran beneficio sería que los _diffs_ podrían ser más eficientes, descartando una línea de 80 columnas en vez de [un párrafo completo en una sóla línea](https://github.com/esparta/97cosas/commit/51715fb9f228832cdb672bef2941756c20fb10c6).

Estoy comenzando este formateo en mi [fork](https://github.com/xiam/97cosas/tree/gh-pages), haré el pull request conforme vaya probando que no se rompen cosas.

**Comment by esparta** [comment]
Me parece bien, sería cosa de probar que Jekyll no se ponga roñoso (o maraku, el plugin que hace la _magia_).

**Comment by esparta** [comment]
Ya hice las pruebas y tal parece que Jekyll + kramdown (el plugin que ahora estoy usando en lugar de maraku) no tiene ningún inconveniente en tomar los saltos de línea nuevos.

Actualmente estoy haciendo correciones ortográficas (puntos, comas, puntos y comas, etc) que ya me esta pasando la persona que contraté para ello, asi que voy integrando los cambios según pase por los archivos. Ahora mismo estoy reformateando con vi ( v + gq), que es lo que conozco.

La primera prueba está en https://raw.github.com/esparta/97cosas/gh-pages/programador/actua-con-prudencia.md

**Comment by esparta** [comment]
Ya están todos los archivos con 80 caracteres (max) por línea. Si encuentra(n)s algún error, por favor avisen.
